# Generated by Django 5.0.6 on 2024-06-16 13:34

import django.db.models.deletion
import products.helps
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.helps.SaveMediaFiles.blog_image_path)),
                ('name', models.CharField(max_length=150)),
                ('by_who', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='products_bl_id_6877eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.helps.SaveMediaFiles.product_image_path)),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('price_type', models.CharField(choices=[('EURO', 'EURO'), ('$', '$'), ('SO`M', 'SO`M')], max_length=4)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='products_pr_id_b46934_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.helps.SaveMediaFiles.clientcomment_image_path)),
                ('name', models.CharField(max_length=80)),
                ('staff_type', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='products_te_id_31d41d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.helps.SaveMediaFiles.clientcomment_image_path)),
                ('name', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='products_cl_id_7bb8b8_idx')],
            },
        ),
    ]
