# Generated by Django 5.0.6 on 2024-06-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cartitem_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full Name')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('telegram_id', models.CharField(max_length=100, verbose_name='Telegram ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
