# Generated by Django 5.0.6 on 2024-06-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_users_delete_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.CharField(unique=True, verbose_name='Telegram ID'),
        ),
    ]
