# Generated by Django 5.0.6 on 2024-06-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_users_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
